alter table USER_FAILED_WORD_INFO drop constraint FK76757535C3088F0;
alter table USER_FAILED_WORD_INFO drop constraint FK76757535DA14584;
alter table USER_UNIT_INFO drop constraint FK4A327315C3088F0;
alter table WORD_UNIT_ENTRY drop constraint FKD913BE2CC3088F0;
drop table USER_ENTRY;
drop table USER_FAILED_WORD_INFO;
drop table USER_UNIT_INFO;
drop table USER_WORD_STUDYING_INFO;
drop table WORD_ENTRY;
drop table WORD_UNIT;
drop table WORD_UNIT_ENTRY;
drop sequence SEQ_USER_ENTRY;
drop sequence SEQ_WORD_ENTRY;
drop sequence SEQ_WORD_UNIT;
create table USER_ENTRY (USER_ID int8 not null, SYS_MSG_ENABLE bool not null, CHATABLE bool not null, JID varchar(100) not null unique, NICK_NAME varchar(100) not null unique, ECHOABLE bool, LOCALE varchar(3) not null, primary key (USER_ID));
create table USER_FAILED_WORD_INFO (USER_ENTRY_ID int8 not null, WORD_UNIT_ID int8 not null, WORD_ENTRY_ID int8 not null, FAILED_COUNTS int8 not null, STUDIED_TIMES int8 not null, LAST_STUDIED timestamp not null, primary key (USER_ENTRY_ID, WORD_UNIT_ID, WORD_ENTRY_ID));
create table USER_UNIT_INFO (USER_ENTRY_ID int8 not null, WORD_UNIT_ID int8 not null, STUDIED_TIMES int8, FINISHED bool, LAST_STUDIED timestamp, primary key (USER_ENTRY_ID, WORD_UNIT_ID));
create table USER_WORD_STUDYING_INFO (USER_ENTRY_ID int8 not null, STUDYING_TYPE int4 not null, FINISHED_UNITS int8 not null, LAST_STUDIED timestamp not null, STUDYING_WORD_UNIT_ID int8, PRIVATE_WORD_UNIT_ID int8, primary key (USER_ENTRY_ID));
create table WORD_ENTRY (WORD_ENTRY_ID int8 not null, COMMENTS varchar(2000), MEANING varchar(200) not null, PRONOUNCE varchar(100) not null, PRONOUNCE_TYPE varchar(2), SENTENCE varchar(2000), WORD varchar(100) not null unique, WORD_TYPE varchar(100), primary key (WORD_ENTRY_ID));
create table WORD_UNIT (WORD_UNIT_ID int8 not null, NAME varchar(100) not null unique, OWNER int8, LEVEL int8 not null, WORD_COUNT int8 not null, primary key (WORD_UNIT_ID));
create table WORD_UNIT_ENTRY (WORD_ENTRY_ID int8 not null, WORD_UNIT_ID int8 not null, primary key (WORD_ENTRY_ID, WORD_UNIT_ID));
alter table USER_FAILED_WORD_INFO add constraint FK76757535C3088F0 foreign key (WORD_UNIT_ID) references WORD_UNIT;
alter table USER_FAILED_WORD_INFO add constraint FK76757535DA14584 foreign key (WORD_ENTRY_ID) references WORD_ENTRY;
alter table USER_UNIT_INFO add constraint FK4A327315C3088F0 foreign key (WORD_UNIT_ID) references WORD_UNIT;
alter table WORD_UNIT_ENTRY add constraint FKD913BE2CC3088F0 foreign key (WORD_UNIT_ID) references WORD_UNIT;
create sequence SEQ_USER_ENTRY;
create sequence SEQ_WORD_ENTRY;
create sequence SEQ_WORD_UNIT;
